platforms:
  win32: res
  ios: resIOS
  android: resAndroid

project:
  path: D:/project_tmp
  config_out: config
  unit_out: src/arena

unit_design_path:
  D:\xmind\

config_path:
  E:\svn\product\配置文件