platforms:
  win32: res
  ios: resIOS
  android: resAndroid

project:
  name: "Test out"
  path: D:\sources\clitool\examples\out
  config_out: config
  unit_out: src/ai

unit_design_path:
  D:\sources\clitool\examples\xmind\design

config_path:
  E:\svn\product\配置文件