platforms:
  win32: res
  ios: resIOS
  android: resAndroid

project:
  name: "magic math"
  path: /yourProjectPath
  config_out: config
  unit_out: src/ai

unit_design_path:
  /xmind/unit_design

config_path:
  /配置文件